language: node_js
sudo: false
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
before_install:
  - pip install --user coveralls
after_success:
  - coveralls --file coverage/lcov.info --disable search